# Generated by Django 5.0.7 on 2024-07-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
